import { useState } from 'react';
import type { MedleySong, EasterEgg } from '../types';
import { getCamelotCode } from '../camelot';
import { exportAbletonAls, type AbletonVersion } from '../ableton';

interface ExportPanelProps {
  songs: MedleySong[];
  eggs: EasterEgg[];
}

function getDecadeLabel(year: number): string {
  if (year < 1950) return 'The Sprint (1926–1949)';
  return `${Math.floor(year / 10) * 10}s`;
}

function exportAsMarkdown(songs: MedleySong[], eggs: EasterEgg[]): string {
  const lines: string[] = [];
  lines.push('# The Hundred Years\' Medley — Running Order\n');

  const totalSeconds = songs.reduce((s, song) => s + song.snippet_duration, 0);
  lines.push(`**Total Runtime:** ${Math.floor(totalSeconds / 60)}:${(totalSeconds % 60).toString().padStart(2, '0')}`);
  lines.push(`**Total Songs:** ${songs.length}\n`);

  // Group by decade
  const decades: Record<string, MedleySong[]> = {};
  songs.forEach((s) => {
    const d = getDecadeLabel(s.year);
    if (!decades[d]) decades[d] = [];
    decades[d].push(s);
  });

  const decadeOrder = ['The Sprint (1926–1949)', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];

  for (const decade of decadeOrder) {
    const decadeSongs = decades[decade];
    if (!decadeSongs || decadeSongs.length === 0) continue;

    const decadeSeconds = decadeSongs.reduce((s, song) => s + song.snippet_duration, 0);
    const avgBpm = Math.round(decadeSongs.reduce((s, song) => s + song.bpm, 0) / decadeSongs.length);

    lines.push(`\n## ${decade}`);
    lines.push(`*${decadeSongs.length} songs · ${Math.floor(decadeSeconds / 60)}:${(decadeSeconds % 60).toString().padStart(2, '0')} · avg ${avgBpm} BPM*\n`);
    lines.push('| # | Year | Song | Artist | BPM | Key | Camelot | Section | Bars | Duration | Transition | Notes |');
    lines.push('|---|------|------|--------|-----|-----|---------|---------|------|----------|------------|-------|');

    decadeSongs.forEach((song, idx) => {
      const transition = song.transition_in ? song.transition_in.replace('_', ' ').toUpperCase() : (idx === 0 ? '—' : 'HARD CUT');
      const flags = [
        song.crowd_moment ? 'SING' : '',
        song.easter_egg ? 'EGG' : '',
        song.horn_friendly ? 'HRN' : '',
      ].filter(Boolean).join(', ');
      const notes = [flags, song.arrangement_notes].filter(Boolean).join('. ');

      lines.push(
        `| ${idx + 1} | ${song.year} | ${song.title} | ${song.artist} | ${song.bpm} | ${song.key} | ${getCamelotCode(song.key)} | ${song.section || 'chorus'} | ${song.bar_count || 16} | ${song.snippet_duration}s | ${transition} | ${notes} |`
      );
    });
  }

  // Easter Eggs section
  if (eggs.length > 0) {
    lines.push('\n## Easter Eggs\n');
    lines.push('| Source Song | Source Decade | Host Decade | Difficulty | Notes |');
    lines.push('|------------|--------------|-------------|------------|-------|');
    eggs.forEach((egg) => {
      lines.push(`| ${egg.source_song} | ${egg.source_decade} | ${egg.host_decade} | ${egg.difficulty} | ${egg.notes} |`);
    });
  }

  lines.push('\n---');
  lines.push('*Generated by Marvin\'s Arranger*');

  return lines.join('\n');
}

function exportAsCsv(songs: MedleySong[]): string {
  const headers = ['Year', 'Title', 'Artist', 'BPM', 'Key', 'Camelot', 'Genre', 'Energy', 'Section', 'Bars', 'Duration (s)', 'Transition', 'Vocal Gender', 'Horn Friendly', 'Keyboard Driven', 'Guitar Driven', 'Crowd Moment', 'Easter Egg', 'Notes'];
  const lines = [headers.join(',')];

  songs.forEach((song) => {
    const row = [
      song.year,
      `"${song.title}"`,
      `"${song.artist}"`,
      song.bpm,
      `"${song.key}"`,
      getCamelotCode(song.key),
      `"${song.genre}"`,
      song.energy,
      song.section || 'chorus',
      song.bar_count || 16,
      song.snippet_duration,
      song.transition_in || 'hard_cut',
      song.vocal_gender,
      song.horn_friendly ? 'Yes' : 'No',
      song.keyboard_driven ? 'Yes' : 'No',
      song.guitar_driven ? 'Yes' : 'No',
      song.crowd_moment ? 'Yes' : 'No',
      song.easter_egg ? 'Yes' : 'No',
      `"${song.arrangement_notes || ''}"`,
    ];
    lines.push(row.join(','));
  });

  return lines.join('\n');
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ExportPanel({ songs, eggs }: ExportPanelProps) {
  const [abletonVersion, setAbletonVersion] = useState<AbletonVersion>('11');
  const totalSeconds = songs.reduce((s, song) => s + song.snippet_duration, 0);

  return (
    <div style={styles.container}>
      <h3 style={styles.title}>Export</h3>

      <div style={styles.summary}>
        <div>{songs.length} songs in medley</div>
        <div>{Math.floor(totalSeconds / 60)}:{(totalSeconds % 60).toString().padStart(2, '0')} total runtime</div>
        <div>{eggs.length} Easter eggs</div>
      </div>

      <div style={styles.buttons}>
        <button
          className="primary"
          onClick={() => {
            const md = exportAsMarkdown(songs, eggs);
            downloadFile(md, 'hundred-years-medley.md', 'text/markdown');
          }}
          disabled={songs.length === 0}
        >
          Export Markdown
        </button>
        <button
          onClick={() => {
            const csv = exportAsCsv(songs);
            downloadFile(csv, 'hundred-years-medley.csv', 'text/csv');
          }}
          disabled={songs.length === 0}
        >
          Export CSV
        </button>
        <button
          onClick={() => {
            const data = {
              songs: songs,
              easterEggs: eggs,
              exportDate: new Date().toISOString(),
              totalRuntime: totalSeconds,
            };
            downloadFile(JSON.stringify(data, null, 2), 'hundred-years-medley.json', 'application/json');
          }}
          disabled={songs.length === 0}
        >
          Export JSON
        </button>

        <div style={styles.abletonRow}>
          <button
            onClick={() => exportAbletonAls(songs, abletonVersion)}
            disabled={songs.length === 0}
            style={styles.abletonBtn}
          >
            Export Ableton .als
          </button>
          <div style={styles.versionToggle}>
            <button
              onClick={() => setAbletonVersion('11')}
              style={abletonVersion === '11' ? styles.versionActive : styles.versionInactive}
            >
              11
            </button>
            <button
              onClick={() => setAbletonVersion('12')}
              style={abletonVersion === '12' ? styles.versionActive : styles.versionInactive}
            >
              12
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: 12,
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 8,
  },
  summary: {
    fontSize: 11,
    color: 'var(--text-secondary)',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    marginBottom: 12,
  },
  buttons: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  abletonRow: {
    display: 'flex',
    gap: 6,
    alignItems: 'stretch',
    marginTop: 4,
  },
  abletonBtn: {
    flex: 1,
  },
  versionToggle: {
    display: 'flex',
    borderRadius: 4,
    overflow: 'hidden',
    border: '1px solid var(--border)',
  },
  versionActive: {
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 700,
    border: 'none',
    background: 'var(--text-primary)',
    color: 'var(--bg-primary)',
    cursor: 'pointer',
  },
  versionInactive: {
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 600,
    border: 'none',
    background: 'var(--bg-tertiary)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
};
